# Generated by Django 3.0.8 on 2023-08-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEcommerceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransaction',
            name='transaction_description',
            field=models.CharField(max_length=255),
        ),
    ]
